-- The existing table has no columns required by the onboarding endpoint.
-- This is safe only because the table currently contains no data.
DROP TABLE IF EXISTS public.looking_for;

CREATE TABLE public.looking_for (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL,
    candidate_name text NOT NULL DEFAULT '',
    roles text[] NOT NULL DEFAULT '{}',
    minimum_salary_lakhs integer NOT NULL DEFAULT 28,
    work_modes text[] NOT NULL DEFAULT '{}',
    job_types text[] NOT NULL DEFAULT '{}',
    availability text NOT NULL DEFAULT 'In 30 days',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT looking_for_email_key UNIQUE (email)
);

-- Remove the UNRESTRICTED status and keep this private table inaccessible
-- to browser clients. The backend service role bypasses RLS.
ALTER TABLE public.looking_for ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.looking_for FROM anon, authenticated;
